#ifndef IOP_CORE_CERTSTORE_HPP
#define IOP_CORE_CERTSTORE_HPP

#include "driver/cert_store.hpp"

namespace iop {

/// Individual certificate structure.
/// Contains certificate array, its size. And its hash.
///
/// Points to PROGMEM data
struct Cert {
  uint16_t size;
  const uint8_t *index;
  const uint8_t *cert;

  constexpr Cert(const uint8_t *cert, const uint8_t *index, const uint16_t size) noexcept:
    size(size), index(index), cert(cert) {}
};

/// Abstracts hardcoded certificates. The instantiation should be auto-generated by the build script.
///
/// The script downloads certificates and generates a header file with them (/include/generated/certificates.hpp)
///
/// _Only_ pass pointers _from_ the PROGMEM to this class
///
/// Pointer's are just borrowed, this structure _must_ outlive the storage.
///
/// Install it with `CertStore::setCertList(...)`
/// The device will panic if the cert store is not installed
class CertList {
  const uint16_t *sizes;
  const uint8_t *const *indexes;
  const uint8_t *const *certs;
  uint16_t numberOfCertificates;

public:
  CertList(const uint8_t *const *certs, const uint8_t *const *indexes,
           const uint16_t *sizes, uint16_t numberOfCertificates) noexcept:
      sizes(sizes), indexes(indexes), certs(certs),
      numberOfCertificates(numberOfCertificates) {}

  auto cert(uint16_t index) const noexcept -> Cert;
  auto count() const noexcept -> uint16_t;
};

/// TLS certificate storage to be installed into BearSSL::WiFiClientSecure. You must construct it from the
/// certs generated by the build script. Check the (build/preBuildCertificates.py)
///
/// It should be stored in static memory. It's not copyable, nor movable.
class CertStore : public BearSSL::CertStoreBase {
  std::unique_ptr<BearSSL::X509List> x509;
  CertList certList;

public:
  explicit CertStore(CertList list) noexcept: x509{}, certList(list) {}

  CertStore(CertStore const &other) noexcept = delete;
  CertStore(CertStore &&other) noexcept = delete;
  auto operator=(CertStore const &other) noexcept -> CertStore & = delete;
  auto operator=(CertStore &&other) noexcept -> CertStore & = delete;
  ~CertStore() noexcept final = default;

  /// Called by libraries like `iop::Network`. Call `iop::Network::setCertList` before making a TLS connection.
  ///
  /// Panics if CertList is not set with `iop::Network::setCertList`.
  void installCertStore(br_x509_minimal_context *ctx) final;

private:
  // These need to be static as they are called from from BearSSL C code
  // Panics if maybeCertList is None. Used to find appropriate cert for the connection

  static auto findHashedTA(void *ctx, void *hashed_dn, size_t len)
      -> const br_x509_trust_anchor *;
  static void freeHashedTA(void *ctx, const br_x509_trust_anchor *ta);
};
} // namespace iop

#endif
